"""Compile the single book model. Use --write, --check, or --render web|pdf|all.

Generated files are committed for IDE previews; CI rejects stale outputs.
Generation happens BEFORE Quarto reads project configuration, never in a
pre-render hook that would silently apply a changed hierarchy one build late.
"""
from __future__ import annotations

import argparse
import hashlib
from copy import deepcopy
import json
import os
from pathlib import Path
import shutil
from string import Template
import subprocess
import sys

import yaml
from book_model import ROOT, documents, load_book


class Dumper(yaml.SafeDumper):
    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow, False)


def yaml_text(value):
    return '# Generated by scripts/build_book.py; edit content/book.json or config/publication.json.\n' + yaml.dump(value, Dumper=Dumper, allow_unicode=True, sort_keys=False, width=110)


def generated_files(root=ROOT):
    model = load_book(root)
    docs = documents(model)
    config = json.loads((root/'config/publication.json').read_text(encoding='utf8'))
    tokens = json.loads((root/'design-system/tokens.json').read_text(encoding='utf8'))
    web_tokens, pdf_tokens = tokens['web'], tokens['pdf']
    html = deepcopy(config['html'])
    html['css'] = [f'styles/{name}.css' for name in ('tokens','base','typography','layout','components','utilities','print','responsive')]
    html['css'].append('assets/pdf-figures/tokens.css')
    html['grid']['body-width'] = web_tokens['mf1-content-width']
    html['filters'] = ['filters/mf1-html-print-figures.lua', {'at':'post-quarto','path':'filters/mf1-html-components.lua'}]
    book = dict(model['book'])
    book.update({'site-url':model['site_url'],'repo-url':model['repo_url'],'date':'last-modified',
        'chapters':['index.qmd'] + [model['documents'][key]['path'] for key in model['frontmatter']] +
            [{'part':part['title'],'chapters':[model['documents'][key]['path'] for key in part['chapters']]} for part in model['parts']],
        'appendices':[model['documents'][key]['path'] for key in model['appendices']],
        'sidebar':{'style':'docked','search':True,'collapse-level':3},
        'page-navigation':True,
        'page-footer':{'left':model['book']['title'],'right':model['book']['author']}})
    base = {'project':{'type':'book','output-dir':'_site','render':['index.qmd']+[d['path'] for d in docs]+['chapters/za_ispis.qmd'],
        'resources':config['project']['resources'],'pre-render':['python scripts/build_book.py --check --config-only']},
        'lang':config['lang'],'language':config['language'],'author':model['book']['author'],
        'bibliography':config['bibliography'],'book':book,'execute':config['execute'],
        'filters':['filters/mf1-components.lua','filters/mf1-editorial-normalization.lua'],
        'format':{'html':html},'editor':'visual'}
    typst = deepcopy(config['typst'])
    typst.update({'papersize':pdf_tokens['paper'],'margin':{'x':f"{pdf_tokens['margin_x_mm']}mm",'y':f"{pdf_tokens['margin_y_mm']}mm"},
        'fontsize':f"{pdf_tokens['font_size_pt']}pt",'mainfont':pdf_tokens['font_family'],
        'linestretch':pdf_tokens['line_stretch'],'linkcolor':web_tokens['mf1-accent-d'],'citecolor':web_tokens['mf1-muted'],
        'filters':[{'at':'post-quarto','path':'filters/mf1-typst-author-blocks.lua'}]})
    profile = {'project':{'output-dir':'_book','render':['index.qmd']+[d['path'] for d in docs]},'format':{'typst':typst}}
    print_profile={'project':{'type':'website','output-dir':'_site','render':['chapters/za_ispis.qmd']},
                   'website':{'title':model['book']['title']}}
    result = {'_quarto.yml':yaml_text(base),'_quarto-pdf.yml':yaml_text(profile),'_quarto-print.yml':yaml_text(print_profile),
        'chapters/_metadata.yml':'# Chapter behaviour is defined once in the project configuration.\n{}\n',
        'index.qmd':'---\npage-layout: article\ntoc: false\nmf1-document-id: home\n---\n\n# '+model['book']['title']+' {.unnumbered .mf1-home-title}\n\n{{< include source/index.md >}}\n'}
    template = Template((root/'components/chapter.qmd.tmpl').read_text(encoding='utf8'))
    for doc in docs:
        wrapper = template.substitute(title=json.dumps(doc['title'],ensure_ascii=False),identifier=doc['id'],kind=doc['kind'],number=json.dumps(doc['number']),source=doc['source'])
        if doc['kind']=='frontmatter':
            wrapper=wrapper.replace('title: '+json.dumps(doc['title'],ensure_ascii=False)+'\n','')
            wrapper=wrapper.replace('<!-- Generated',f"# {doc['number']}. {doc['title']} {{.unnumbered}}\n\n<!-- Generated")
        result[doc['path']]=wrapper
    result['chapters/za_ispis.qmd'] = print_collection(docs)
    result['docs/kanonska-struktura-sadrzaja.md']=canonical_map(docs)
    result['assets/book-model.json']=json.dumps({'book':model['book'],'parts':model['parts'],'documents':docs},ensure_ascii=False,indent=2)+'\n'
    # The answer appendix is another view of the same Problem objects.
    from generate_exercise_key import build as exercise_key
    answer=next(doc for doc in docs if doc.get('role')=='answers')
    result[answer['source']]=exercise_key(root)
    font_import=f"@import url('{tokens['web_font_import']}');\n" if tokens.get('web_font_import') else ''
    result['styles/tokens.css']='/* Generated from design-system/tokens.json. */\n'+font_import+':root {\n'+''.join(f'  --{k}: {v};\n' for k,v in web_tokens.items())+'}\n'
    result['design-system/quarto-theme.scss']=f'''/* Generated Bootstrap defaults, before component styles. */
/*-- scss:defaults --*/
$primary: {web_tokens['mf1-accent-d']};
$link-color: {web_tokens['mf1-accent-d']};
$body-color: {web_tokens['mf1-ink']};
$body-bg: {web_tokens['mf1-bg']};
$font-family-serif: {web_tokens['mf1-serif']};
$font-family-sans-serif: {web_tokens['mf1-sans']};
$font-family-base: $font-family-serif;
$headings-font-family: $font-family-sans-serif;
'''
    for name in ('responsive','print'):
        path=root/f'styles/{name}.css.in'
        if path.exists():
            values={**tokens['breakpoints'],**pdf_tokens}
            result[f'styles/{name}.css']=Template(path.read_text(encoding='utf8')).substitute(values)
    result['assets/typst/mf1-tokens.typ']='// Shared values; generated by scripts/build_book.py.\n'+ '\n'.join(
        f'#let mf1-{key.replace("_","-")} = {json.dumps(value,ensure_ascii=False)}' for key,value in pdf_tokens.items())+'\n'+''.join(
        f'#let {key} = rgb("{value}")\n' for key,value in web_tokens.items() if value.startswith('#'))
    return result


def canonical_map(docs):
    text='''# Kanonska struktura sadržaja

<!-- Generirano iz content/book.json; ne uređivati ručno. -->

Hijerarhija, naslovi i putanje uređuju se u `content/book.json`, a tekst u
navedenom izvoru. Omotači nastaju iz zajedničkog predloška. Broj poglavlja
određuje položaj u modelu; stabilni ID i javna putanja ne mijenjaju se pri
premještanju. Pravila proširenja opisuje [arhitektura](arhitektura.md).

| Oznaka | Kanonski omotač | Izvor |
| --- | --- | --- |
'''
    for doc in docs:text+=f"| {doc['number']} | `{doc['path']}` | `{doc['source']}` |\n"
    return text+'\nDodatak s kontrolnim rezultatima također se generira iz zadataka. Pokreni `python scripts/build_book.py --write` nakon izmjene izvora ili modela.\n'


def print_collection(docs):
    text='''---
title: "MF1 — pregled za ispis u pregledniku"
subtitle: "Za pripremljen prijelom stranica preuzmi PDF priručnika"
page-layout: article
toc: false
number-sections: false
mf1-print-collection: true
---

<!-- Generated from the shared book hierarchy. -->
::: {.mf1-print-note .no-print}
Za pripremljen prijelom stranica, sadržaj i bibliografiju preuzmi [PDF priručnika](../downloads/mehanika-fluida-1.pdf). Ova stranica služi brzom ispisu iz preglednika.
:::

```{=html}
<nav class="mf1-print-toolbar no-print" aria-label="Ispis knjige">
<button class="mf1-print-button" data-mf1-print-button>Ispiši / Spremi kao PDF</button>
<a class="mf1-print-button secondary" href="../index.html">Povratak na početnu stranicu</a>
</nav>
```

'''
    for doc in docs:
        text+=f"# {doc['title']} {{#print-{doc['id']} .mf1-collection-chapter .unnumbered data-document=\"{doc['id']}\"}}\n\n"
        text+='{{< include ../'+doc['source']+' >}}\n\n'
    return text.rstrip()+'\n'


def compile_book(write=False, config_only=False, root=ROOT):
    sync_figure_tokens(root, write)
    outputs=generated_files(root)
    stale=[]
    for name,text in outputs.items():
        path=root/name
        if not path.exists() or path.read_text(encoding='utf8')!=text:
            if write:
                path.parent.mkdir(parents=True,exist_ok=True);path.write_text(text,encoding='utf8',newline='\n')
            else:stale.append(name)
    if stale:
        raise ValueError('Generated book files are stale: '+', '.join(stale)+'. Run: python scripts/build_book.py --write')
    if not config_only:
        from content_index import build_index
        path=root/'assets/content-index.json'
        content=json.dumps(build_index(root),ensure_ascii=False,indent=2)+'\n'
        if not path.exists() or path.read_text(encoding='utf8')!=content:
            if write:path.write_text(content,encoding='utf8',newline='\n')
            else:raise ValueError('Content index is stale. Run: python scripts/build_book.py --write')
        outputs['assets/content-index.json']=content
    return len(outputs)


def figure_text_width(pdf):
    """Physical canvas follows page margins; labels keep their own point size."""
    if pdf['paper'].lower() != 'a4':
        raise ValueError('Figure geometry currently supports A4; define paper dimensions before changing paper size.')
    width = round((210 - 2 * pdf['margin_x_mm']) * 72 / 25.4, 3)
    if width <= 0:raise ValueError('PDF margins leave no content width')
    return width


def sync_figure_tokens(root, write):
    design=json.loads((root/'design-system/tokens.json').read_text(encoding='utf8'))
    path=root/design['figure_tokens']
    tokens=json.loads(path.read_text(encoding='utf8'))
    width=figure_text_width(design['pdf'])
    if tokens['text-width-pt'] != width:
        if not write:raise ValueError('Figure width is stale; run python scripts/build_book.py --write')
        tokens['text-width-pt']=width
        path.write_text(json.dumps(tokens,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='\n')
    manifest_path=root/'assets/pdf-figures/manifest.json'
    manifest=json.loads(manifest_path.read_text(encoding='utf8')) if manifest_path.exists() else {}
    stale=not manifest
    for name,digest in manifest.get('inputs',{}).items():
        actual=hashlib.sha256((root/name).read_text(encoding='utf8').encode()).hexdigest()
        stale=stale or actual!=digest
    for name,figure in manifest.get('figures',{}).items():
        actual=hashlib.sha1((root/'assets/print'/name).read_text(encoding='utf8').encode()).hexdigest()
        stale=stale or actual!=figure['source_sha1']
    if stale:
        if not write:raise ValueError('Print figures are stale; run python scripts/build_book.py --write')
        subprocess.run(['node','tools/build_print_figures.mjs'],cwd=root,check=True)


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write',action='store_true');parser.add_argument('--check',action='store_true')
    parser.add_argument('--config-only',action='store_true');parser.add_argument('--render',choices=['web','pdf','all'])
    args=parser.parse_args()
    if args.render:
        from render_workspace import build_lock, render
        quarto=shutil.which('quarto')
        if not quarto:raise SystemExit('Quarto must be installed and available on PATH.')
        with build_lock(ROOT):
            count=compile_book(write=True,config_only=args.config_only)
            print(f'Book model generated: {count} outputs.', flush=True)
            render(ROOT,args.render,quarto)
    else:
        count=compile_book(write=args.write,config_only=args.config_only)
        print(f'Book model {"generated" if args.write else "PASS"}: {count} outputs.')


if __name__=='__main__':
    try:main()
    except ValueError as exc:raise SystemExit(str(exc)) from exc
